services:
  nbc:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: nbc
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - /srv/catalog:/srv/catalog
      - /srv/import:/srv/import
    restart: unless-stopped
